"""
magisk.py — Magisk module builder, installer, and manager
Build systemless mods that survive OTA updates
"""
import click
import zipfile
import shutil
from pathlib import Path
from datetime import datetime
from modules import run_adb, adb_devices, OUTPUT_DIR, WORKSPACE, console


# ── Module template ──────────────────────────────────────────────────────────

MODULE_PROP_TEMPLATE = """\
id={id}
name={name}
version={version}
versionCode={version_code}
author={author}
description={description}
"""

CUSTOMIZE_SH = """\
#!/system/bin/sh
# Magisk Module Install Script — generated by WatchROM

SKIPUNZIP=0

# Abort on incompatible Magisk version
require_new_magisk() {
    ui_print "*******************************"
    ui_print " Please install Magisk v20.4+! "
    ui_print "*******************************"
    abort
}

[ "$MAGISK_VER_CODE" -lt 20400 ] && require_new_magisk

ui_print "- Installing {name}"
ui_print "- Version: {version}"
"""

SERVICE_SH = """\
#!/system/bin/sh
# Module service script — runs after boot
# Add persistent prop changes, start services, etc.

# Example: set props on boot
# resetprop ro.debuggable 1
"""

POST_FS_SH = """\
#!/system/bin/sh
# post-fs-data.sh — runs in post-fs-data phase
# Good for: replacing system files, bind mounts

MODDIR="${0%/*}"

# Example: overlay a system file
# mount --bind "$MODDIR/system/etc/hosts" /system/etc/hosts
"""


def create_module_structure(mod_dir: Path, meta: dict):
    """Scaffold a Magisk module directory."""
    mod_dir.mkdir(parents=True, exist_ok=True)

    # module.prop
    (mod_dir / "module.prop").write_text(MODULE_PROP_TEMPLATE.format(**meta))

    # Scripts
    _name = meta['name']
    _ver  = meta['version']
    _csh  = '#!/system/bin/sh\n'
    _csh += '# Magisk Module Installer\n'
    _csh += 'SKIPUNZIP=0\n'
    _csh += 'ui_print "Installing ' + _name + ' ' + _ver + '"\n'
    (mod_dir / "customize.sh").write_text(_csh)
    (mod_dir / "post-fs-data.sh").write_text("#!/system/bin/sh\n# Post-fs-data script\n")

    # System overlay directories
    for d in ["system/app", "system/priv-app", "system/etc",
              "system/bin", "system/lib", "system/lib64", "system/framework"]:
        (mod_dir / d).mkdir(parents=True, exist_ok=True)
        (mod_dir / d / ".gitkeep").touch()

    # README
    (mod_dir / "README.md").write_text(
        f"# {meta['name']}\n\n{meta['description']}\n\n"
        f"Generated by WatchROM Magisk Module Builder\n\n"
        f"## Structure\n"
        f"- `system/`         — Files overlaid onto /system (no APKs needed in /data)\n"
        f"- `service.sh`      — Runs after boot (for setprop, etc.)\n"
        f"- `post-fs-data.sh` — Runs post-fs-data (for bind mounts)\n"
        f"- `customize.sh`    — Runs during install in Magisk\n"
    )

    return mod_dir


def pack_module(mod_dir: Path, out_zip: Path):
    """Pack module directory into installable Magisk zip."""
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as z:
        for f in mod_dir.rglob("*"):
            if f.name == ".gitkeep":
                continue
            if f.is_file():
                arcname = f.relative_to(mod_dir)
                z.write(f, arcname)
    return out_zip


# ── CLI ───────────────────────────────────────────────────────────────────────

@click.group()
def magisk():
    """Magisk module builder, installer, and device module manager."""
    pass


@magisk.command("create")
@click.option("--id",          "mod_id",  required=True, help="Module ID (no spaces, e.g. watchrom_tweaks)")
@click.option("--name",        "-n",      required=True, help="Human-readable name")
@click.option("--version",     "-v",      default="v1.0")
@click.option("--author",      "-a",      default="WatchROM")
@click.option("--description", "-d",      default="WatchROM Magisk Module")
@click.option("--out",         "-o",      default=None,  help="Output directory")
def magisk_create(mod_id, name, version, author, description, out):
    """
    Scaffold a new Magisk module with full directory structure.

    Creates:
      module.prop      — Module metadata
      customize.sh     — Install-time script
      service.sh       — Boot-time script (setprop, etc.)
      post-fs-data.sh  — Early-boot script (bind mounts)
      system/          — Systemless overlay tree
    """
    meta = {
        "id":           mod_id,
        "name":         name,
        "version":      version,
        "version_code": int(datetime.now().strftime("%Y%m%d")),
        "author":       author,
        "description":  description,
    }

    out_dir = Path(out) if out else (OUTPUT_DIR / "magisk_modules" / mod_id)
    console.print(f"\n[bold cyan]Magisk Module Builder[/bold cyan]")
    console.print(f"  ID     : {mod_id}")
    console.print(f"  Name   : {name}")
    console.print(f"  Output : {out_dir}\n")

    create_module_structure(out_dir, meta)

    console.print(f"[green]✓ Module scaffolded: {out_dir}[/green]")
    console.print(f"\n[bold]Next steps:[/bold]")
    console.print(f"  1. Add files to [cyan]{out_dir}/system/[/cyan]")
    console.print(f"     e.g. APKs → system/app/<AppName>/<AppName>.apk")
    console.print(f"  2. Edit [cyan]service.sh[/cyan] for persistent props")
    console.print(f"  3. Pack: [bold]watchrom magisk pack {out_dir}[/bold]")
    console.print(f"  4. Install: [bold]watchrom magisk install <module.zip>[/bold]")


@magisk.command("pack")
@click.argument("module_dir")
@click.option("--out", "-o", default=None, help="Output zip path")
def magisk_pack(module_dir, out):
    """Pack a Magisk module directory into an installable zip."""
    mod_dir = Path(module_dir)
    if not mod_dir.is_dir():
        console.print(f"[red]✗ Not a directory: {module_dir}[/red]")
        return

    prop_file = mod_dir / "module.prop"
    if not prop_file.exists():
        console.print(f"[red]✗ module.prop not found — not a valid Magisk module dir[/red]")
        return

    # Read module id for naming
    props = dict(l.split("=",1) for l in prop_file.read_text().splitlines() if "=" in l)
    mod_id = props.get("id", mod_dir.name)
    ver    = props.get("version", "v1").replace(" ","_")

    out_zip = Path(out) if out else (OUTPUT_DIR / "magisk_modules" / f"{mod_id}_{ver}.zip")
    out_zip.parent.mkdir(parents=True, exist_ok=True)

    console.print(f"[cyan]Packing module: {mod_id} {ver}[/cyan]")
    pack_module(mod_dir, out_zip)

    from modules import file_size_mb, sha256_file
    console.print(f"[green]✓ Module zip: {out_zip}[/green]")
    console.print(f"  Size  : {file_size_mb(out_zip):.2f} MB")
    console.print(f"  SHA256: {sha256_file(out_zip)[:32]}…")
    console.print(f"\n  Install: [bold]watchrom magisk install {out_zip}[/bold]")


@magisk.command("install")
@click.argument("module_zip")
@click.option("--serial", "-s", default=None)
def magisk_install(module_zip, serial):
    """Push and install a Magisk module zip on device."""
    devs = adb_devices()
    online = [s for s, st in devs if st == "device"]
    if not online:
        console.print("[red]✗ No ADB device.[/red]")
        return
    target = serial or online[0]

    zip_path = Path(module_zip)
    if not zip_path.exists():
        console.print(f"[red]✗ Not found: {module_zip}[/red]")
        return

    remote = f"/sdcard/Download/{zip_path.name}"
    console.print(f"[cyan]→ Pushing {zip_path.name} to device...[/cyan]")
    rc, _, err = run_adb(["push", str(zip_path), remote], serial=target, check=False, timeout=120)
    if rc != 0:
        console.print(f"[red]✗ Push failed: {err}[/red]")
        return

    # Install via Magisk CLI
    _, out, _ = run_adb(
        ["shell", f"su -c 'magisk --install-module {remote}'"],
        serial=target, check=False, timeout=60
    )
    console.print(out.strip())

    if "Done" in out or "success" in out.lower():
        console.print(f"[green]✓ Module installed. Reboot to activate.[/green]")
    else:
        console.print(f"[yellow]! Check Magisk app to complete installation.[/yellow]")
        console.print(f"  Module file on device: {remote}")


@magisk.command("list")
@click.option("--serial", "-s", default=None)
def magisk_list(serial):
    """List installed Magisk modules on device."""
    devs = adb_devices()
    online = [s for s, st in devs if st == "device"]
    if not online:
        console.print("[red]✗ No ADB device.[/red]")
        return
    target = serial or online[0]

    _, out, _ = run_adb(
        ["shell", "su -c 'cat /data/adb/modules/*/module.prop 2>/dev/null'"],
        serial=target, check=False
    )

    console.print(f"\n[bold cyan]Installed Magisk Modules — {target}[/bold cyan]\n")

    if not out.strip():
        console.print("[dim]No modules found (or device not rooted).[/dim]")
        return

    # Parse module.prop blocks
    current = {}
    for line in out.splitlines():
        line = line.strip()
        if "=" in line:
            k, v = line.split("=", 1)
            current[k] = v
        elif not line and current:
            name = current.get("name", "?")
            ver  = current.get("version", "?")
            desc = current.get("description", "")
            console.print(f"  [green]✓[/green] [bold]{name}[/bold] {ver}  [dim]{desc[:60]}[/dim]")
            current = {}

    if current:
        name = current.get("name","?")
        ver  = current.get("version","?")
        desc = current.get("description","")
        console.print(f"  [green]✓[/green] [bold]{name}[/bold] {ver}  [dim]{desc[:60]}[/dim]")


@magisk.command("prop-module")
@click.option("--id",   "mod_id", default="watchrom_props")
@click.option("--out",  "-o",     default=None)
@click.option("--set",  "-s",     "pairs", multiple=True,
              help="key=value pair (can repeat)")
def magisk_prop_module(mod_id, out, pairs):
    """
    Quick-build a Magisk module that sets persistent system properties.

    Example:
      watchrom magisk prop-module --id my_tweaks \\
        --set ro.debuggable=1 \\
        --set ro.secure=0 \\
        --set persist.sys.usb.config=mtp,adb
    """
    if not pairs:
        console.print("[red]✗ No props specified. Use --set key=value[/red]")
        return

    prop_lines = []
    for pair in pairs:
        if "=" in pair:
            prop_lines.append(pair)

    service_sh = "#!/system/bin/sh\n# Auto-generated prop module\n\n"
    for line in prop_lines:
        k, v = line.split("=", 1)
        service_sh += f"resetprop {k} {v}\n"

    out_dir = Path(out) if out else (OUTPUT_DIR / "magisk_modules" / mod_id)
    meta = {
        "id":           mod_id,
        "name":         f"Props: {mod_id}",
        "version":      "v1.0",
        "version_code": "1",
        "author":       "WatchROM",
        "description":  f"Sets {len(prop_lines)} system properties",
    }
    create_module_structure(out_dir, meta)
    (out_dir / "service.sh").write_text(service_sh)

    zip_path = out_dir.parent / f"{mod_id}.zip"
    pack_module(out_dir, zip_path)
    console.print(f"[green]✓ Prop module: {zip_path}[/green]")
    console.print(f"  Props included:")
    for line in prop_lines:
        console.print(f"    [cyan]{line}[/cyan]")
    console.print(f"\n  Install: [bold]watchrom magisk install {zip_path}[/bold]")
