"""
twrp.py — TWRP device configuration scaffolding and build helper
Generates BoardConfig, device.mk, recovery UI config, and build script
"""
import click
from pathlib import Path
from datetime import datetime
from modules import (
    run_adb, adb_devices, get_device_props, detect_chipset_from_props,
    OUTPUT_DIR, WORKSPACE, console
)


# ─── Templates ────────────────────────────────────────────────────────────────

def make_board_config(info: dict) -> str:
    vendor   = info["vendor"]
    device   = info["device"]
    arch     = info["arch"]
    chipset  = info["chipset"]
    platform = info["platform"]
    has_ab   = info.get("ab_partitions", False)
    screen_x = info.get("screen_x", 360)
    screen_y = info.get("screen_y", 360)

    ab_block = """
# A/B partitions
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \\
    boot \\
    system \\
    vendor
""" if has_ab else ""

    return f"""\
#
# BoardConfig.mk — generated by WatchROM TWRP Builder
# Device  : {vendor}/{device}
# Chipset : {chipset}
# Created : {datetime.now().strftime("%Y-%m-%d")}
#

LOCAL_PATH := device/{vendor}/{device}

# Platform
TARGET_BOARD_PLATFORM := {platform}
TARGET_NO_BOOTLOADER  := true
TARGET_NO_RADIOIMAGE  := true

# Architecture
TARGET_ARCH         := {arch}
TARGET_ARCH_VARIANT := {arch}
TARGET_CPU_ABI      := {info.get("abi","arm64-v8a")}
TARGET_CPU_ABI2     :=
TARGET_CPU_VARIANT  := generic

# Kernel
TARGET_PREBUILT_KERNEL           := $(LOCAL_PATH)/prebuilt/Image.gz-dtb
BOARD_KERNEL_CMDLINE             := console=ttyS1,115200n8 androidboot.hardware={device} androidboot.selinux=permissive
BOARD_KERNEL_BASE                := 0x00000000
BOARD_KERNEL_PAGESIZE            := 2048
BOARD_RAMDISK_OFFSET             := 0x01000000
BOARD_KERNEL_TAGS_OFFSET         := 0x00000100
BOARD_MKBOOTIMG_ARGS             += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS             += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

# Partitions
BOARD_FLASH_BLOCK_SIZE              := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE      := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE  := 67108864
BOARD_SYSTEMIMAGE_PARTITION_SIZE    := 3221225472
BOARD_VENDORIMAGE_PARTITION_SIZE    := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE  := 4294967296
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE  := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE  := ext4

TARGET_USERIMAGES_USE_EXT4         := true
TARGET_USERIMAGES_USE_F2FS         := true
{ab_block}

# Recovery
TW_THEME                 := portrait_hdpi
RECOVERY_SDCARD_ON_DATA  := true
TW_BRIGHTNESS_PATH       := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS        := 255
TW_DEFAULT_BRIGHTNESS    := 150
TW_SCREEN_BLANK_ON_BOOT  := true
TW_INPUT_BLACKLIST       := "hbtp_vm"
TW_USE_TOOLBOX           := true
TW_HAS_NO_RECOVERY_PARTITION := false

# Display
TW_FRAMERATE             := 60
TW_CUSTOM_CPU_TEMP_PATH  := /sys/class/thermal/thermal_zone0/temp

# Screen resolution for smartwatch
TW_SCREEN_WIDTH          := {screen_x}
TW_SCREEN_HEIGHT         := {screen_y}

# Crypto — disable for testing
TW_INCLUDE_CRYPTO        := false

# Debug
TWRP_INCLUDE_LOGCAT      := true
TARGET_USES_LOGD         := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

# AVB
BOARD_AVB_ENABLE         := false
"""


def make_device_mk(info: dict) -> str:
    vendor = info["vendor"]
    device = info["device"]
    return f"""\
#
# device.mk — generated by WatchROM TWRP Builder
#
LOCAL_PATH := device/{vendor}/{device}

# Soong namespaces
PRODUCT_SOONG_NAMESPACES += $(LOCAL_PATH)

# Use the default AOSP product
$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/base.mk)

PRODUCT_DEVICE := {device}
PRODUCT_NAME   := twrp_{device}
PRODUCT_BRAND  := {info.get("brand","generic")}
PRODUCT_MODEL  := {info.get("model","Smartwatch")}
PRODUCT_MANUFACTURER := {vendor}
"""


def make_omni_manifest(info: dict) -> str:
    vendor = info["vendor"]
    device = info["device"]
    return f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!--
  local_manifests/roomservice.xml
  Add this to .repo/local_manifests/ in your TWRP source tree
-->
<manifest>
  <project name="device_{vendor}_{device}"
           path="device/{vendor}/{device}"
           remote="github"
           revision="android-12.1" />
</manifest>
"""


def make_build_script(info: dict) -> str:
    vendor = info["vendor"]
    device = info["device"]
    return f"""\
#!/usr/bin/env bash
# WatchROM — TWRP Build Script
# Device: {vendor}/{device}
# Generated: {datetime.now().strftime("%Y-%m-%d")}
#
# Prerequisites:
#   - Ubuntu 20.04+ (18GB+ RAM recommended)
#   - TWRP source: repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
#   - Place device tree in: device/{vendor}/{device}/
#
set -e

DEVICE="{device}"
VENDOR="{vendor}"
TWRP_SOURCE="${{HOME}}/twrp"

echo "=== WatchROM TWRP Builder ==="
echo "Device : $VENDOR/$DEVICE"

# Sync device tree
mkdir -p "$TWRP_SOURCE/.repo/local_manifests"
cp roomservice.xml "$TWRP_SOURCE/.repo/local_manifests/"
cd "$TWRP_SOURCE"
repo sync --no-clone-bundle -j$(nproc) device/$VENDOR/$DEVICE

# Setup environment
source build/envsetup.sh

# Select target
lunch twrp_${{DEVICE}}-eng

# Build recovery image
mka recoveryimage -j$(nproc) 2>&1 | tee build_${{DEVICE}}.log

# Output
OUT_IMG="out/target/product/$DEVICE/recovery.img"
if [ -f "$OUT_IMG" ]; then
    cp "$OUT_IMG" ~/watchrom_twrp_${{DEVICE}}.img
    echo "✓ TWRP image: ~/watchrom_twrp_${{DEVICE}}.img"
else
    echo "✗ Build failed — check build_${{DEVICE}}.log"
    exit 1
fi
"""


# ─── CLI ──────────────────────────────────────────────────────────────────────

@click.group()
def twrp():
    """TWRP recovery device configuration and build script generator."""
    pass


@twrp.command("build")
@click.option("--serial",   "-s", default=None, help="ADB serial to auto-detect device info")
@click.option("--vendor",   "-v", default=None, help="Manufacturer (e.g. ticwatch)")
@click.option("--device",   "-d", default=None, help="Device codename (e.g. catfish)")
@click.option("--platform", "-p", default=None, help="Board platform (e.g. sc9863a)")
@click.option("--arch",     "-a",
              type=click.Choice(["arm","arm64","x86","x86_64"]), default="arm64")
@click.option("--screen",   "-S", default="360x360",
              help="Screen resolution WxH (default: 360x360 for watch)")
@click.option("--ab",       is_flag=True, help="Device has A/B partitions")
@click.option("--out",      "-o", default=None)
def twrp_build(serial, vendor, device, platform, arch, screen, ab, out):
    """
    Generate a TWRP device tree scaffold for a smartwatch.

    If --serial is provided, auto-reads device props to fill in details.
    Output includes BoardConfig.mk, device.mk, roomservice.xml, build.sh
    """
    info = {}

    # Auto-detect from device
    if serial:
        devs = adb_devices()
        online = [s for s, st in devs if st == "device"]
        if online:
            target = serial if serial in [s for s,_ in online] else online[0]
            props = get_device_props(target)
            chip_vendor, chip = detect_chipset_from_props(props)
            info = {
                "vendor":   vendor  or props.get("ro.product.manufacturer","").lower() or "unknown",
                "device":   device  or props.get("ro.product.device","").lower() or "unknown",
                "brand":    props.get("ro.product.brand","generic"),
                "model":    props.get("ro.product.model","Smartwatch"),
                "chipset":  chip,
                "platform": platform or props.get("ro.board.platform", chip.lower()),
                "arch":     arch,
                "abi":      props.get("ro.product.cpu.abi","arm64-v8a"),
                "ab_partitions": ab or props.get("ro.build.ab_update","false") == "true",
            }
            console.print(f"[dim]Auto-detected: {info['vendor']}/{info['device']} ({chip})[/dim]")
        else:
            console.print("[yellow]! Device not found via ADB — using manual inputs.[/yellow]")

    # Manual override / fill gaps
    info.setdefault("vendor",   vendor   or click.prompt("Manufacturer (e.g. ticwatch)", default="unknown"))
    info.setdefault("device",   device   or click.prompt("Device codename", default="watch1"))
    info.setdefault("platform", platform or click.prompt("Board platform", default="sc9863a"))
    info.setdefault("chipset",  info["platform"])
    info.setdefault("arch",     arch)
    info.setdefault("ab_partitions", ab)
    info.setdefault("brand",  info["vendor"])
    info.setdefault("model",  info["device"])
    info.setdefault("abi",    "arm64-v8a" if arch == "arm64" else "armeabi-v7a")

    try:
        sx, sy = map(int, screen.lower().split("x"))
    except Exception:
        sx, sy = 360, 360
    info["screen_x"] = sx
    info["screen_y"] = sy

    out_dir = Path(out) if out else (OUTPUT_DIR / "twrp" / f"{info['vendor']}_{info['device']}")
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "prebuilt").mkdir(exist_ok=True)

    # Write files
    files = {
        "BoardConfig.mk":  make_board_config(info),
        "device.mk":       make_device_mk(info),
        "roomservice.xml": make_omni_manifest(info),
        "build.sh":        make_build_script(info),
        "Android.mk": (
            f"LOCAL_PATH := $(call my-dir)\n"
            f"ifeq ($(TARGET_DEVICE),{info['device']})\n"
            f"include $(call all-makefiles-under,$(LOCAL_PATH))\n"
            f"endif\n"
        ),
        "AndroidProducts.mk": (
            f"PRODUCT_MAKEFILES := $(LOCAL_DIR)/device.mk\n"
            f"COMMON_LUNCH_CHOICES := twrp_{info['device']}-eng\n"
        ),
    }

    for filename, content in files.items():
        path = out_dir / filename
        with open(path, "w") as f:
            f.write(content)
        console.print(f"[green]✓[/green] {filename}")

    # Placeholder for kernel
    (out_dir / "prebuilt" / "README.txt").write_text(
        "Place your prebuilt kernel Image.gz-dtb here.\n"
        "Extract from stock boot.img: watchrom dump boot\n"
        "Then: unpackbootimg -i boot.img\n"
    )

    console.print(f"\n[bold green]✓ TWRP device tree: {out_dir}[/bold green]")
    console.print(f"\n[bold]Next steps:[/bold]")
    console.print(f"  1. Place kernel in [cyan]{out_dir}/prebuilt/Image.gz-dtb[/cyan]")
    console.print(f"  2. Review and tune [cyan]BoardConfig.mk[/cyan] (partition sizes, kernel args)")
    console.print(f"  3. Run [cyan]bash {out_dir}/build.sh[/cyan] in your TWRP source tree")
    console.print(f"  4. Flash: [cyan]fastboot flash recovery out/.../recovery.img[/cyan]")
